version: "3.7"

x-nodebase: &nodebase
   build: .
   restart: on-failure
   volumes:
      - "./files:/var/files"

x-nodeserver: &nodeserver
   <<: *nodebase
   environment:
      - REDIS_HOST=cache
   depends_on:
      - redis

x-nodeapp: &nodeapp
   <<: *nodebase
   environment:
      - SERVER_HOST=api:3001
   depends_on:
      - server

x-nodeworker: &nodeworker
   <<: *nodebase
   environment:
      - REDIS_HOST=cache
      - SERVER_HOST=api:3001
   depends_on:
      - redis
      - server

services:
   redis:
      image: redis
      container_name: cache
      volumes:
         - "./.data/redis:/var/lib/redis/data"
      expose:
         - 6379
      command: redis-server

   app:
      <<: *nodeapp
      ports:
         - 3000:3000
      command: sh -c 'yarn build && yarn projector'

   server:
      <<: *nodeserver
      container_name: api
      ports:
         - 3001:3001
      command: sh -c 'yarn server'

   scraper:
      <<: *nodeworker
      command: sh -c 'yarn scraper'

   importer:
      <<: *nodeworker
      command: sh -c 'yarn importer'

   slicer:
      <<: *nodeworker
      command: sh -c 'yarn slicer'

   runner:
      <<: *nodeworker
      command: sh -c 'yarn runner'
