version: "3.7"

x-node: &node
   build: .
   restart: on-failure
   volumes:
      - "./files:/var/files"
   environment:
      - REDIS_HOST=cache
   depends_on:
      - redis

services:
   redis:
      image: redis
      command: redis-server
      container_name: cache
      volumes:
         - "./.data/redis:/var/lib/redis/data"
      expose:
         - 6379

   app:
      <<: *node
      ports:
         - 3000:3000
      environment:
         - NODE_ENV=production
      command: sh -c 'yarn build && yarn projector'

   server:
      <<: *node
      container_name: api
      ports:
         - 3001:3001
      command: sh -c 'yarn server'

   scraper:
      <<: *node
      command: sh -c 'yarn scraper'

   importer:
      <<: *node
      command: sh -c 'yarn importer'
      depends_on:
         - server
      environment:
         - SERVER_HOST=api:3001
   slicer:
      <<: *node
      command: sh -c 'yarn slicer'
      depends_on:
         - server
      environment:
         - SERVER_HOST=api:3001
